name: "Setup Project"
description: "Install pnpm, node and dependencies"
runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320
      with:
        package_json_file: ./package.json

    - name: Setup Node
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
      with:
        node-version-file: ./.node-version
        cache: "pnpm"
        cache-dependency-path: ./pnpm-lock.yaml
        registry-url: https://registry.npmjs.org
        scope: "@digitalservicebund"

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
