name: Deploy Storybook for a Branch (Manual Trigger)

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch to deploy"
        required: true

jobs:
  build-and-deploy-storybook:
    runs-on: ubuntu-latest
    concurrency:
      group: "pages"
      cancel-in-progress: true
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout selected branch
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup
        uses: ./.github/actions/setup-project

      - name: Build Storybook
        run: pnpm run build:storybook

      - name: Setup Pages
        uses: actions/configure-pages@45bfe0192ca1faeb007ade9deae92b16b8254a0d

      - name: Upload Storybook artifact
        uses: actions/upload-pages-artifact@7b1f4a764d45c48632c6b24a0339c27f5614fb0b
        with:
          path: ./storybook-static

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@vcd2ce8fcbc39b97be8ca5fce6e763baed58fa128
