name: Release to npm

on:
  # manual
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0
      - name: Setup
        uses: ./.github/actions/setup-project
      - name: Build
        run: pnpm run build
      - run: pnpm dlx --package semantic-release@beta semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
